### PR TITLE
Added support for Message and JSONMessage

### PR DESCRIPTION
**Pull request by vinaysshenoy**
Added support for Message and JSONMessage messages to SocketIOClient.

### CODE REVIEW

**Comment by koush** [comment]
Could you clean up the diff please?

**Comment by vinaysshenoy** [comment]
I'm pretty new to Github and the etiquette we are supposed to be following, so could you please elaborate a bit on what you mean by cleaning up the diff? Thanks.

**Comment by koush** [comment]
If you click "Files Changed" you can see that the entire file has completely changed. This is due to whitespace and/or tab reformatting. This is generally considered a bad practice for a couple reasons:
- I can't see what the change was
- It breaks git blame and history

Fixing the diff means minimizing the diff to only what you changed: so your change is apparent in this diff, without the extra noise.

**Comment by vinaysshenoy** [comment]
Ah, I see. My Eclipse auto formatting seems to have done this. I'll close this pull request and open another one with a fixed up diff.

**Comment by koush** [comment]
thx

**Pull request closed without merging**
