### PR TITLE
Fixed double firing of onConnect().

### PR DESCRIPTION
**Pull request by mike-stewart**
Fixed issue where the onConnect() event in a SocketIOClient handler is fired twice for a single connection: once from the run() method in WebSocketClient, and once from the onMessage() event in SocketIOClient. It would seem that the later is redundant.

### CODE REVIEW

**Comment by koush** [comment]
Good catch.

Should probably actually comment out the other one, as that is when the socketio handshake is actually completed and connected.

**Comment by mike-stewart** [comment]
Thanks for the tip. I've switched it to use the other onConnect() call, which is the one that is called second and therefore ensures that the connection is complete.

**Comment by koush** [comment]
wrong one, that breaks the WebSocket onConnect callback for any pure websocket consumers.

The one you want is line 242 in SocketIOClient.

**Comment by mike-stewart** [comment]
That doesn't solve the problem, as then the onConnect() method in the handler is never called. Both of the onConnect() calls I mention above call the onConnect() method on line 234 of SocketIOClient (an implementation of the WebSocketClient listener), which in turn calls the onConnect() method in the SocketIO handler (line 242). 

It seems that we need to get rid of one of the onConnect() calls that I mentioned in the initial pull request. My initial thinking was that we should get rid of the one in SocketIOClient so as to not break pure websocket clients, but as you say the one in WebSocketClient is called earlier than the one in SocketIOClient, so there is the risk that we're calling it before SocketIO has finished handshaking.

Thoughts?

**Comment by koush** [comment]
Ah gotcha.

Maybe move replace line 132 with line 242?

So 

``` java
onConnect();
```

becomes

``` java
 mHandler.onConnect();
```

That way, the websocket client code remains untouched and working.

This removes the duplicate call to

``` java
mHandler.onConnect();
```

as then it would only be called once the socket IO handshake is actually complete, and not _also_ when the web socket connection is made.

**Comment by mike-stewart** [comment]
That works for my application as well. Definitely a more robust solution. I've pushed the fix, thanks!

**Pull request merged**
