### PR TITLE
Added Support for Acknowledges

### PR DESCRIPTION
**Pull request by vinaysshenoy**

### CODE REVIEW

**Comment by vinaysshenoy** [comment]
Fixed Updated README getting overwritten by documention for Acknowledges.

**Comment by koush** [comment]
can't merge automatically, mind rebasing?

**Comment by vinaysshenoy** [comment]
I don't mind doing it, but I'm not too experienced with git and I don't know how the rebase command works...

**Comment by vinaysshenoy** [comment]
Could you please try now? I tried a rebase...

**Comment by vinaysshenoy** [comment]
Could you please try merging now? It should work...

**Comment by vinaysshenoy** [comment]
Thanks. Incidentally, the LearnBoost Socket.IO documentation mentions that this library is now deprecated. If this is true, then will any additions to the AndroidAsync Socket.IO library be merged back into this?

**Comment by koush** [comment]
Yes, I do plan to beef up that version, but you're more than welcome to as well as I'm totally swamped. :)

There's a few open issues on there; people want channel support etc. That's missing from this library as well.

**Comment by vinaysshenoy** [comment]
Ah, I see. Thanks.

Channel support? Do you mean endpoints/namespaces? I believe I added support for these pretty recently into this library.

**Comment by koush** [comment]
Oh, right, so you did! Completely forgot.

Curiously, I thought socket.io allows multiplexing of the connection, so you can be connected to multiple endpoints through a single websocket connection? Or is that not the case with the websocket transport?

**Comment by vinaysshenoy** [comment]
Actually, it does. I added in namespace support for an app I was working on, and even when I connected to multiple namespaces, I still received messages from every other namespace I was connected to. The namespace from which the message came was included in the message, so you can separate them based on that(I don't know if this was intentional or how the server guy coded the server, however).

That's why I added the onConnectToEndpoint() method, as you can maintain a list of the endpoints you are connected to.

But our app needed to be connected to only one endpoint at a time, so I added the sendDisconnect() method to disconnect from the previous endpoint as well.

**Pull request merged**
