### PR TITLE
Add support to message endPoint

### PR DESCRIPTION
**Pull request by Wicowyn**
Add support of message endPoint for types : message, message JSON and event

(like in the Socket.io specification: https://github.com/LearnBoost/socket.io-spec)

### CODE REVIEW

**Comment by koush** [comment]
@vinaysshenoy Please review :)

**Comment by ghost** [comment]
We had an issue with doing something something similar in one of our projects. The server wouldn't accept messages unless an endpoint was left out. At the same time, it also wouldn't accept another event unless we specifically directed it to an endpoint.

Instead of adding it by default, it would be better to pass an endpoint in the method parameters. That way, you can send messages to multiple endpoints in the same socket client.

**Comment by koush** [comment]
I'd check out AndroidAsync. I just recently revamped the socket.io support to add this, and a lot of other stuff.

**Comment by Wicowyn** [comment]
Good idea :) is true that the call of onMessage function (and other) under worker thread is a bit annoying. So, good luck.

**Comment by ghost** [comment]
@koush AndroidAsync is good, but there are a lot of people who need a Socket.IO client to supplement their own(or another) networking library. I'd prefer not to import a whole new library just for using one component of it.

Might be useful to accept valid pull requests to keep this maintained.. :-)

**Comment by koush** [comment]
@sourcebits-vinaysshenoy fair enough, was just being lazy about resolving the merge conflict :)

**Comment by ghost** [comment]
yeah, I know the feeling.. :-)

Anyway, this still needs a modification though.. Adding the endpoint should be optional for emit messages like I mentioned earlier.. I'll submit a pull request later tonight..

Full disclosure: I'm planning to repurpose this same library into a custom fork of Volley.. So I'm pretty invested in keeping this updated.. ;-)

**Comment by koush** [comment]
What's the purpose of putting it into volley? Once the websocket upgrade takes place, the underlying http library is taken out of the picture completely.

**Comment by koush** [comment]
In fact, no http library is used at all at the moment. Raw sockets, hah.

**Comment by ghost** [comment]
Yeah, I know.. But I'm maintaining a custom fork with which I plan to include plug in components for different things(Socket.IO, XMPP, OAuth.).. Rather than being a fork of Volley, it'd actually be a networking solution which uses Volley for APIs, Socket.IO for well, socket.io and so..

**Comment by koush** [comment]
@sourcebits-vinaysshenoy Ah gotcha.

For what it's worth, the recent (this weekend) changes in AndroidAsync solve a lot of the problems and issues that have been opened on android-websockets library recently. It may be worth looking at it to check out the new design, and implement/port the changes into this standalone library.

In particular:
- endpoint support (and multiplexing them through a single connection)
- acknowledgements (send/receive)
- automatic reconnects
- event emitters

The equivalent ported changes will break the API, but that's not a bad thing.

I'm only saying this, because I doubt I will have the time to port it over :)

**Comment by ghost** [comment]
Yup, I'll go through it and see what I can do. The older library seemed to getting a bit unwieldy anyway. Maybe a new branch?

I know you're a bit biased(:P), but what would you say to using ION as the HttpStack on Volley? Are the performance improvements noticeable?

**Comment by koush** [comment]
I briefly looked into doing that; it wouldn't work (at least not without a lot of mangling) to add a shim to HTTPUrlConnection and blocking inputstreams.

**Comment by vinaysshenoy** [comment]
Ah, I see. Too bad.

**Comment by koush** [comment]
Yeah, we can branch off the current code into a v1 branch, and make a new master branch.

**Comment by vinaysshenoy** [comment]
All right.. I've forked the AsyncHttp repo.. I'll take a look at the Socket.IO implementation tomorrow and see the best way to port it.

**Comment by koush** [comment]
It should be relatively straightforward. It's built on top of the same HybiParser and WebSocket (which have only been slightly modified).

**Comment by vinaysshenoy** [comment]
I'm going through it now and it seems to be done pretty nicely. It won't be too much trouble to completely port it. A day or two at the max. The main thing is that the SocketIOConnection is analogous to your earlier SocketIOClient, right? One SocketIOConnection per socket url, multiplexing SocketIOClients for endpoints...

What took me more time(almost the whole day) was to get a local Socket.IO server set up. I'd never worked with Maven before and the server implementation required it. m2Eclipse is a nice tool, but the documentation is terrible.. I was blundering around for quite a while before I figured out how to build and deploy the server. At least, I've got it running now to test during the port process.

**Comment by koush** [comment]
Oh, I just use a node.js socket.io server. Easy as hell to set up.

**Comment by koush** [comment]
Yeah, I had to decouple the bit related to transport management from the bit related to endpoint management. The code makes more sense now.

**Comment by vinaysshenoy** [comment]
Yeah, I have no experience with node whatsoever and I thought it would be easier to spin up a Java server.. Boy, was I wrong.

**Comment by koush** [comment]
I'd actually recommend using the node.js server to test, as that is the "reference" implementation provided by LearnBoost. I'm sure any third party implementation is sure to have quirks and other random features. Looking at the implementation of endpoints that have been committed here, I'm 99% sure that won't work on the node.js server implementation (it certainly didn't while I was writing endpoint support).

ie... http://example.com/socket.io/1/ is a valid http request 

but, http://example.com/myendpoint/1/ isn't a valid http request (404), at least on the reference implementation.

You must connect to the default endpoint first, then connect to myendpoint from within that session.

**Comment by vinaysshenoy** [comment]
@koush Yeah, I know. We never customized the default endpoint in the constructor in our project, so we didn't run into this issue.

Anyway, the port is complete. I've done some basic testing with a node server, and I'm receiving events successfully on the client and am connecting and disconnecting from endpoints. How should we proceed?

Before pushing the code, I still need to refactor and test it a bit, so maybe another day or two before the v2 version of android-websockets is ready for usage.

**Comment by koush** [comment]
Just send a pull rqeuest, and I can review. I'll probably fork the current branch into a 1.x .

**Pull request merged**
