### PR TITLE
Use ANDROID_HOME environment variable to locate SDK

### PR DESCRIPTION
**Pull request by vkotovv**
Just updated build.xml via command `android update project --path android-websockets` to get an option to locate SDK with env variable. Was introduced in one of the recent versions of SDK tools.
This could be helpful for using Jenkins to build project depending on the android-websockets library.

### CODE REVIEW

**Comment by koush** [comment]
use local.properties to set up sdk.dir. That's how this is supposed to be done.

```
# This file is automatically generated by Android Tools.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.

# location of the SDK. This is only used by Ant
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=/Users/koush/src/android-sdk
```

**Comment by vkotovv** [comment]
Yes, that's true that one option is to use local.properties. This is one way of how it's supposed to be done. However, this piece of code was added to the SDK tools to provide alternative method. What I'm trying to say that build.xml was generated a year ago and now is outdated. If you use `android update project` command for the fresh project, this snippet will be there, you can try. So my idea was to update build.xml to the latest version. Please refer to [similar request](https://github.com/loopj/android-async-http/pull/110).
Regarding Jenkins build, it is easier to set $ANDROID_HOME variable once rather than adding local.properties for every Jenkins job.

**Comment by koush** [comment]
Oh gotcha. I've refreshed the build.xml w/ the android sdk locally and pushed. Thanks for the notice.

**Comment by koush** [comment]
https://github.com/koush/android-websockets/commit/a6a3b99fb032bd2fc96c0d8d0275b4eed830acfd

**Comment by vkotovv** [comment]
No problem, thanks for updating this.

**Pull request closed without merging**
